version: "3.3"
services:
  app:
    image: sameersbn/redmine
    environment:
      - DB_HOST=db
      - DB_NAME=redmine_production
      - DB_USER=rootredmine
      - DB_PASS=p4ssw0rd4redmine
    links:
      - db
    depends_on:
      - db
    ports:
      - 80:8080
    volumes:
      - ./:/home/redmine/redmine/plugins/redmine_plugin/
  db:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=pa4ssw0rd4mysql
      - MYSQL_DATABASE=redmine_production
